name: Semantic Release
on:
  push:
    branches:
      - "develop"
    paths:
      - "chakra-ui-steps/*"
defaults:
  run:
    working-directory: chakra-ui-steps
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
